name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: dependancy-installer
      run: sudo apt-get update -y && sudo apt-get install -y libboost-all-dev
    - name: build
      run: make
